In [2]:
import tarfile
  
# open file
file = tarfile.open('./languageID.tgz')
  
# extracting file
file.extractall('./train_data')
  
file.close()

In [3]:
y_label = ['e', 'j', 's']
import numpy as np

In [4]:
char_count = np.zeros([3,20,27])
for k, label in enumerate(y_label):
    print(label);
    #print(k);
    #char_count = np.zeros([3,10,27])
    for i in range(20):
        print('train_data/languageID/%s'%label+'%d'%i+'.txt')
        f = open('train_data/languageID/%s' % label+ '%d' % i+'.txt')
        data = f.read();
        for j in data:
            if((j!='\n')):
                if((j == ' ')):
                    char_count[k][i][26] += 1;
                else:
                    char_count[k][i][ord(j)-97] += 1;
        #print("space_count =",char_count[26]);
        print("count =", char_count[k][i])
               
        

e
train_data/languageID/e0.txt
count = [ 67.   8.  28.  25. 142.  16.  12.  66.  61.   0.   9.  46.  25.  75.
  88.  17.   0.  72.  76. 100.  38.  13.  28.   0.  16.   1. 236.]
train_data/languageID/e1.txt
count = [ 69.   5.  10.  23. 108.  16.   8.  48.  51.   3.   1.  22.  25.  43.
  59.  12.   0.  57.  73.  87.  27.   6.  15.   0.  19.   1. 181.]
train_data/languageID/e2.txt
count = [ 40.   8.  15.  17.  92.  18.  15.  43.  44.   0.   5.  20.  13.  41.
  55.  19.   0.  44.  54.  60.  14.   6.  10.   1.   8.   2. 139.]
train_data/languageID/e3.txt
count = [138.  30.  48.  50. 225.  41.  24. 101. 123.   3.   5.  62.  54. 134.
 148.  32.   3. 122. 151. 189.  59.  24.  42.   1.  35.   0. 391.]
train_data/languageID/e4.txt
count = [ 41.   5.  16.  18. 102.  21.  24.  52.  51.   0.   2.  24.  20.  52.
  72.  25.   0.  56.  51.  66.  24.  10.  10.   3.  13.   1. 145.]
train_data/languageID/e5.txt
count = [210.  32.  63.  54. 313.  55.  68. 136. 178.   6.  10. 107.  60. 188.
 179.  46.   1.

In [6]:
likelihood = np.zeros([3,27]);
alpha = 0.5;
for i in range(3):
    print("char count sum :", np.sum(char_count[i][:10],axis=0))
    likelihood[i]= (np.sum(char_count[i][:10],axis=0) + alpha)/(np.sum(np.sum(char_count[i][:10],axis=0)) + 27*alpha) 

char count sum : [ 910.  168.  325.  332. 1594.  286.  264.  714.  838.   21.   56.  438.
  310.  876.  975.  253.    8.  814. 1001. 1212.  403.  140.  234.   17.
  209.    9. 2712.]
char count sum : [1.885e+03 1.550e+02 7.800e+01 2.460e+02 8.610e+02 5.500e+01 2.000e+02
 4.540e+02 1.388e+03 3.300e+01 8.210e+02 2.000e+01 5.690e+02 8.110e+02
 1.304e+03 1.200e+01 1.000e+00 6.120e+02 6.030e+02 8.150e+02 1.010e+03
 3.000e+00 2.820e+02 0.000e+00 2.020e+02 1.100e+02 1.766e+03]
char count sum : [1.695e+03 1.330e+02 6.080e+02 6.440e+02 1.845e+03 1.390e+02 1.160e+02
 7.300e+01 8.080e+02 1.070e+02 4.000e+00 8.580e+02 4.180e+02 8.780e+02
 1.175e+03 3.930e+02 1.240e+02 9.610e+02 1.066e+03 5.770e+02 5.460e+02
 9.500e+01 1.000e+00 4.000e+01 1.270e+02 4.300e+01 2.728e+03]


In [7]:
likelihood

array([[6.01685115e-02, 1.11349744e-02, 2.15099950e-02, 2.19725756e-02,
        1.05369238e-01, 1.89327606e-02, 1.74789361e-02, 4.72162564e-02,
        5.54105402e-02, 1.42078308e-03, 3.73368578e-03, 2.89773666e-02,
        2.05187510e-02, 5.79216917e-02, 6.44639022e-02, 1.67520238e-02,
        5.61704940e-04, 5.38245498e-02, 6.61820585e-02, 8.01255576e-02,
        2.66644639e-02, 9.28465224e-03, 1.54964480e-02, 1.15645135e-03,
        1.38443747e-02, 6.27787874e-04, 1.79249959e-01],
       [1.31765610e-01, 1.08669066e-02, 5.48586603e-03, 1.72263182e-02,
        6.02047591e-02, 3.87854223e-03, 1.40116706e-02, 3.17621161e-02,
        9.70334393e-02, 2.34110207e-03, 5.74094133e-02, 1.43261470e-03,
        3.97987351e-02, 5.67105769e-02, 9.11632132e-02, 8.73545547e-04,
        1.04825466e-04, 4.28037318e-02, 4.21747790e-02, 5.69901115e-02,
        7.06174220e-02, 2.44592753e-04, 1.97421294e-02, 3.49418219e-05,
        1.41514379e-02, 7.72214263e-03, 1.23449457e-01],
       [1.04560451e-01

In [8]:
def predict(x):
    prob = np.zeros(3);
    for i in range(3):
        for j in range(27):
            prob[i] = prob[i] + x[j]*np.log(likelihood[i][j])
    prob_label = np.log(1/3);
    print(prob)
    print(prob+prob_label); 
    return np.argmax(prob+prob_label);
    
predict(char_count[0][10])

[-7841.86544706 -8771.43307908 -8467.28204401]
[-7842.96405935 -8772.53169136 -8468.3806563 ]


0

In [9]:
#test data
pred = np.zeros([3, 10])
for i in range(3):
    for j in range(10):
        pred[i][j] = predict(char_count[i][j+10]);

print(pred)
    

[-7841.86544706 -8771.43307908 -8467.28204401]
[-7842.96405935 -8772.53169136 -8468.3806563 ]
[ -9346.21187506 -10407.28383319 -10056.2521139 ]
[ -9347.31048735 -10408.38244548 -10057.35072619]
[-5285.490455   -5836.36279816 -5681.09371085]
[-5286.58906729 -5837.46141045 -5682.19232314]
[-4742.75350354 -5182.13334878 -5178.66342058]
[-4743.85211583 -5183.23196107 -5179.76203287]
[-4683.03931476 -5181.4771028  -5047.72526661]
[-4684.13792705 -5182.57571509 -5048.8238789 ]
[-4600.23893454 -5033.95182275 -4960.51318253]
[-4601.33754683 -5035.05043504 -4961.61179482]
[-7678.84975509 -8631.73226903 -8289.27692001]
[-7679.94836738 -8632.83088132 -8290.3755323 ]
[-6879.7553713  -7609.76619908 -7355.87446364]
[-6880.85398359 -7610.86481137 -7356.97307593]
[-4598.25099325 -5078.38958947 -4864.17346173]
[-4599.34960553 -5079.48820176 -4865.27207402]
[-1655.85674191 -1817.25793193 -1735.59839096]
[-1656.95535419 -1818.35654422 -1736.69700325]
[-4543.2495348  -4132.78009678 -5003.94991962]
[-4544.